-- 코드를 입력하세요
-- SELECT
--     ANIMAL_ID
-- FROM(
--     SELECT *
--     FROM ANIMAL_INS
--     WHERE NAME IS NOT NULL
-- )
-- ORDER BY ANIMAL_ID

-- SELECT
--     ANIMAL_ID
-- FROM ANIMAL_INS
-- WHERE NAME IS NOT NULL
-- -- WHERE NAME <> NULL
-- ORDER BY ANIMAL_ID

-- SELECT DISTINCT(ANIMAL_ID)
-- FROM ANIMAL_INS
-- WHERE NAME IS NOT NULL
-- ORDER BY ANIMAL_ID;

-- 10/25
SELECT
    ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
ORDER BY ANIMAL_ID;