-- -- 코드를 입력하세요
-- 10/24
SELECT
    L.HOUR AS HOUR,
    NVL(COUNT, 0) AS COUNT
FROM (
    SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME, 'HH24')
    ORDER BY HOUR
    ) O, (
    SELECT LEVEL -1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
    ) L
WHERE L.HOUR = O.HOUR(+)
ORDER BY L.HOUR;