-- 코드를 입력하세요
-- SELECT
--     B.CATEGORY, 
--     SUM(SALES) AS TOTAL_SALES
-- FROM BOOK B, 
-- (
--     SELECT BOOK_ID, SUM(SALES) AS SALES
--     FROM BOOK_SALES
--     WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
--     GROUP BY BOOK_ID
-- )S
-- WHERE B.BOOK_ID = S.BOOK_ID
-- GROUP BY B.CATEGORY
-- ORDER BY CATEGORY;
-- SELECT CATEGORY, SUM(TOTAL_SALES)
-- FROM BOOK B JOIN (
--     SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
--     FROM BOOK_SALES
--     WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
--     GROUP BY BOOK_ID
--     ) S ON S.BOOK_ID = B.BOOK_ID
-- GROUP BY CATEGORY
-- ORDER BY CATEGORY

-- 10/23
SELECT
    B.CATEGORY,
    SUM(S.SALES)
FROM BOOK B JOIN (
    SELECT *
    FROM BOOK_SALES
    WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
) S
                 ON B.BOOK_ID = S.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY