-- -- 코드를 입력하세요
-- -- SELECT
-- --     A.AUTHOR_ID,
-- --     A.AUTHOR_NAME,
-- --     B.CATEGORY,
-- --     B.PRICE * BS.SALES AS TOTAL_SALES
-- -- FROM BOOK B, AUTHOR A, (
-- --     SELECT BOOK_ID, SUM(SALES) AS SALES
-- --     FROM BOOK_SALES
-- --     WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
-- --     GROUP BY BOOK_ID
-- -- )BS
-- -- WHERE BS.BOOK_ID = B.BOOK_ID AND B.AUTHOR_ID = A.AUTHOR_ID
-- -- ORDER BY AUTHOR_ID, CATEGORY DESC
-- SELECT A.AUTHOR_ID, A.AUTHOR_NAME, O.CATEGORY, O.TOTAL_SALES
-- FROM AUTHOR A, (
--     SELECT BS.BOOK_ID, B.AUTHOR_ID, B.CATEGORY, B.PRICE * BS.SALES AS TOTAL_SALES
--     FROM BOOK B, (
--         SELECT BOOK_ID, SUM(SALES) AS SALES
--         FROM BOOK_SALES
--         WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
--         GROUP BY BOOK_ID
--     )BS
--     WHERE B.BOOK_ID = BS.BOOK_ID
-- )O
-- WHERE  O.AUTHOR_ID = A.AUTHOR_ID
-- ORDER BY AUTHOR_ID, CATEGORY DESC

-- SELECT A.AUTHOR_ID, A.AUTHOR_NAME, O.CATEGORY, O.TOTAL_SALES
-- FROM AUTHOR A, (
--     SELECT B.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
--     FROM BOOK B, (
--         SELECT BOOK_ID, SUM(SALES) AS SALES
--         FROM BOOK_SALES
--         WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
--         GROUP BY BOOK_ID
--     )BS
--     WHERE B.BOOK_ID = BS.BOOK_ID
--     GROUP BY AUTHOR_ID, B.CATEGORY
-- )O
-- WHERE A.AUTHOR_ID = O.AUTHOR_ID
-- ORDER BY AUTHOR_ID, CATEGORY DESC

-- 10/23
SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    O.CATEGORY,
    O.TOTAL_SALES
FROM AUTHOR A JOIN (
    SELECT
        B.AUTHOR_ID,
        B.CATEGORY,
        SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
    FROM BOOK B JOIN (
        SELECT BOOK_ID, SUM(SALES) AS SALES
        FROM BOOK_SALES
        WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
        GROUP BY BOOK_ID
    )BS ON B.BOOK_ID = BS.BOOK_ID
    GROUP BY AUTHOR_ID, B.CATEGORY
) O ON A.AUTHOR_ID = O.AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC








