# SELECT
      #     F2.FISH_COUNT,
          #     F1.FISH_NAME
# FROM FISH_NAME_INFO F1 JOIN (
    #     SELECT
#         COUNT(*) AS FISH_COUNT,
#         FISH_TYPE
#     FROM FISH_INFO
#     GROUP BY FISH_TYPE
# )F2 ON F1.FISH_TYPE = F2.FISH_TYPE
      # ORDER BY 1 DESC;
SELECT COUNT(*) AS FISH_COUNT, FISH_NAME
FROM FISH_INFO A
         JOIN FISH_NAME_INFO B
              ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY FISH_NAME
ORDER BY 1 DESC