-- 코드를 입력하세요
-- SELECT
--     CAR_TYPE,
--     COUNT(*) AS CARS
-- FROM CAR_RENTAL_COMPANY_CAR
-- WHERE OPTIONS LIKE '%통풍시트%' OR OPTIONS LIKE '%열선시트%' OR OPTIONS LIKE '%가죽시트%'
-- GROUP BY CAR_TYPE
-- ORDER BY CAR_TYPE

-- SELECT CAR_TYPE, count(OPTIONS)
-- from CAR_RENTAL_COMPANY_CAR
--     where OPTIONS like '%통풍시트%'
--     or OPTIONS like '%열선시트%'
--     or OPTIONS like '%가죽시트%'
-- group by CAR_TYPE
-- order by CAR_TYPE

-- SELECT
--     CAR_TYPE,
--     COUNT(CAR_TYPE) AS CARS
-- FROM(
--     SELECT
--         CAR_TYPE,
--         COUNT(CAR_TYPE) AS CARS,
--         OPTIONS
--     FROM CAR_RENTAL_COMPANY_CAR
--     GROUP BY CAR_TYPE
-- )
-- WHERE OPTIONS LIKE '%통풍시트%' OR OPTIONS LIKE '%열선시트%' OR OPTIONS LIKE '%가죽시트%'
-- ORDER BY CAR_TYPE;


-- SELECT CAR_TYPE, COUNT(*)
-- FROM CAR_RENTAL_COMPANY_CAR
-- WHERE OPTIONS LIKE '%통풍시트%' OR OPTIONS LIKE '%열선시트%' OR OPTIONS LIKE '%가죽시트%'
-- GROUP BY CAR_TYPE
-- ORDER BY CAR_TYPE

-- 10/23
SELECT
    CAR_TYPE,
    COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%통풍시트%'
   OR OPTIONS LIKE '%열선시트%'
   OR OPTIONS LIKE '%가죽시트%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC;
