-- -- 코드를 입력하세요
-- SELECT
--     INGREDIENT_TYPE,
--     SUM(TOTAL_ORDER) AS TOTAL_ORDER
-- FROM (
--     SELECT
--         I.INGREDIENT_TYPE,
--         F.TOTAL_ORDER
--     FROM FIRST_HALF F, ICECREAM_INFO I
--     WHERE F.FLAVOR = I.FLAVOR
-- )INFO
-- GROUP BY INGREDIENT_TYPE
-- SELECT
--     F.FLAVOR,
--     I.INGREDIENT_TYPE,
--     F.TOTAL_ORDER
-- FROM FIRST_HALF F, ICECREAM_INFO I
-- WHERE F.FLAVOR = I.FLAVOR

-- 10/24
SELECT
    I.INGREDIENT_TYPE,
    SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F JOIN ICECREAM_INFO I
                       ON F.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;









