-- 코드를 입력하세요
-- SELECT
--     FOOD_TYPE,
--     REST_ID,
--     REST_NAME,
--     FAVORITES
-- FROM REST_INFO
-- WHERE (FOOD_TYPE, FAVORITES) in (
--     SELECT
--         FOOD_TYPE,
--         MAX(FAVORITES)
--     FROM REST_INFO
--     GROUP BY FOOD_TYPE
-- )
-- ORDER BY FOOD_TYPE DESC

-- 10/23
SELECT
    B.FOOD_TYPE,
    A.REST_ID,
    A.REST_NAME,
    B.FAVORITES
FROM REST_INFO A JOIN (
    SELECT
        FOOD_TYPE,
        MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)B ON A.FAVORITES = B.FAVORITES AND A.FOOD_TYPE = B.FOOD_TYPE
ORDER BY FOOD_TYPE DESC