-- SELECT
--     TO_CHAR(S.START_DATE, 'FMMM') AS MONTH,
--     S.CAR_ID,
--     COUNT(*) AS RECORDS
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY S JOIN (
--     SELECT
--         DISTINCT H1.CAR_ID
--     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H1 JOIN (
--         SELECT
--             CAR_ID,
--             COUNT(*) AS RECORDS
--         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--         WHERE TO_CHAR(START_DATE, 'YYYY-MM') = '2022-08' OR
--             TO_CHAR(START_DATE, 'YYYY-MM') = '2022-09' OR
--             TO_CHAR(START_DATE, 'YYYY-MM') = '2022-10'
--         GROUP BY CAR_ID
--         HAVING COUNT(*) >= 5
--     ) H2 ON H1.CAR_ID = H2.CAR_ID
--     ORDER BY TO_CHAR(H1.START_DATE, 'MM') ASC, H1.CAR_ID DESC
-- ) R ON S.CAR_ID = R.CAR_ID
-- GROUP BY TO_CHAR(S.START_DATE, 'FMMM'), S.CAR_ID
-- ORDER BY TO_NUMBER(MONTH) ASC, S.CAR_ID DESC;

-- 10/23
-- SELECT
--     TO_CHAR(START_DATE, 'FMMM') AS MONTH,
--     CAR_ID,
--     COUNT(*) AS RECORDS
-- FROM
--     CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE
--     TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
-- GROUP BY
--     TO_CHAR(START_DATE, 'FMMM'), CAR_ID
-- HAVING
--     CAR_ID IN (
--         SELECT CAR_ID
--         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--         WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
--         GROUP BY CAR_ID
--         HAVING COUNT(*) >= 5
--     )
-- ORDER BY TO_NUMBER(MONTH) ASC, CAR_ID DESC;

SELECT
    EXTRACT(MONTH FROM S.START_DATE) AS MONTH,
    S.CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY S
    JOIN (
        SELECT
            CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5
    ) R ON S.CAR_ID = R.CAR_ID
WHERE TO_CHAR(S.START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
GROUP BY EXTRACT(MONTH FROM S.START_DATE), S.CAR_ID
ORDER BY EXTRACT(MONTH FROM S.START_DATE) ASC, S.CAR_ID DESC;
