-- 코드를 입력하세요
-- SELECT
--     COUNT(ROWNUM) AS USERS
-- FROM (
--     SELECT *
--     FROM USER_INFO
--     WHERE (AGE BETWEEN 20 and 29) AND (TO_CHAR(JOINED, 'YYYY') = 2021)
-- )AGE

-- SELECT COUNT(*) AS USERS
-- FROM USER_INFO
-- WHERE TO_CHAR(JOINED,'YYYY') = '2021' AND (AGE BETWEEN 20 AND 29);
-- SELECT
--     ROUND((SYSDATE-JOINED) /365, 1) AS AGE
-- FROM USER_INFO

-- 10/11
-- SELECT
--     COUNT(*)
-- FROM USER_INFO
-- WHERE TO_CHAR(JOINED, 'YYYY') = '2021' AND (AGE >= 20 AND AGE <= 29)

SELECT
    COUNT(*)
FROM USER_INFO
WHERE TO_CHAR(JOINED, 'YYYY') = '2021' AND AGE BETWEEN 20 AND 29









