-- 코드를 입력하세요
-- SELECT
--     ANIMAL_ID, NAME
-- FROM (
--     SELECT *
--     FROM ANIMAL_INS
--     WHERE INTAKE_CONDITION = 'Sick'
-- )ANIMAL
-- ORDER BY ANIMAL_ID, NAME

-- SELECT ANIMAL_ID, NAME
-- FROM ANIMAL_INS
-- WHERE INTAKE_CONDITION = 'Sick'
-- ORDER BY ANIMAL_ID, NAME;

-- 10/11
SELECT
    ANIMAL_ID,
    NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'
ORDER BY ANIMAL_ID;

