-- 코드를 입력하세요
-- SELECT
--     BOOK_ID,
--     AUTHOR_NAME,
--     TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
-- FROM (
--     SELECT *
--     FROM BOOK
--     WHERE CATEGORY = '경제'
-- )A
-- JOIN AUTHOR B
-- ON A.AUTHOR_ID = B.AUTHOR_ID
-- ORDER BY PUBLISHED_DATE;

-- SELECT B.BOOK_ID, A.AUTHOR_NAME, TO_CHAR(B.PUBLISHED_DATE, 'YYYY-MM-DD')
-- FROM BOOK B JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
-- WHERE B.CATEGORY = '경제'
-- ORDER BY B.PUBLISHED_DATE

-- 10/28
SELECT
    B.BOOK_ID,
    A.AUTHOR_NAME,
    TO_CHAR(B.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK B JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY B.PUBLISHED_DATE