-- 코드를 입력하세요
-- SELECT
--     C.NAME, C.DATETIME
-- FROM(
--     SELECT
--         DISTINCT A.NAME, A.DATETIME
--     FROM ANIMAL_INS A
--     LEFT JOIN ANIMAL_OUTS B
--     ON A.ANIMAL_ID <> B.ANIMAL_ID
-- )ANIMAL C
-- WHERE ROWNUM = 1 OR ROWNUM = 2 OR ROWNUM = 3
-- ORDER BY DATETIME;

-- SELECT
--     C.NAME AS NAME,
--     C.DATETIME AS DATETIME
-- FROM (
--     SELECT *
--     FROM ANIMAL_INS A
--     JOIN ANIMAL_OUT B
--     ON A.NAME <> B.NAME
-- )ANIMAL C
-- FETCH NEXT 3 ROWS ONLY
-- ORDER BY NAME;

-- SELECT I.NAME, I.DATETIME
-- FROM ANIMAL_INS I
-- LEFT JOIN ANIMAL_OUTS O
-- ON I.ANIMAL_ID = O.ANIMAL_ID
-- WHERE O.ANIMAL_ID IS NULL
-- ORDER BY I.DATETIME
-- FETCH NEXT 3 ROWS ONLY;

-- SELECT I.NAME, I.DATETIME
-- FROM ANIMAL_INS I LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
-- WHERE O.ANIMAL_ID IS NULL
-- ORDER BY I.DATETIME
-- FETCH NEXT 3 ROWS ONLY;

-- 10/28
SELECT
    I.NAME,
    I.DATETIME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID(+)
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME ASC
    FETCH NEXT 3 ROWS ONLY









