-- 코드를 입력하세요
-- SELECT
--     A.ANIMAL_ID, A.NAME
-- FROM ANIMAL_INS I
-- RIGHT JOIN ANIMAL_OUTS A
-- ON I.ANIMAL_ID = A.ANIMAL_ID
-- WHERE I.ANIMAL_ID IS NULL
-- ORDER BY A.ANIMAL_ID, A.NAME;

-- 10/28
SELECT
    O.ANIMAL_ID,
    O.NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID(+) = O.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID, O.NAME;








