-- 코드를 입력하세요
-- SELECT
--     P.PRODUCT_CODE,
--     P.PRICE * O.SALES_AMOUNT AS SALES
-- FROM PRODUCT P
-- JOIN (
--     SELECT PRODUCT_ID, SALES_AMOUNT
--     FROM OFFLINE_SALE
--     GROUP BY PRODUCT_ID
-- )OFFLINE_SALE O
-- ON P.PRODUCT_ID = O.PRODUCT_ID
-- ORDER BY P.PRODUCT_CODE DESC;

-- SELECT
--     -- *
--     P.PRODUCT_CODE,
--     SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
--     -- P.PRICE * SUM(O.SALES_AMOUNT) AS SALES
-- FROM PRODUCT P, OFFLINE_SALE O
-- WHERE P.PRODUCT_ID = O.PRODUCT_ID
-- GROUP BY P.PRODUCT_CODE
-- ORDER BY SALES DESC, P.PRODUCT_CODE;

-- 10/28
SELECT
    P.PRODUCT_CODE,
    P.PRICE * S.TOTAL_SALES AS SALES
FROM PRODUCT P JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_SALES
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) S ON P.PRODUCT_ID = S.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC








