-- 코드를 입력하세요
-- SELECT
--     CAR_ID,
--     ROUND(AVG(DURATION), 1) AS AVERAGE_DURATION
-- FROM(
--     SELECT
--         HISTORY_ID,
--         CAR_ID,
--         END_DATE - START_DATE + 1 AS DURATION
--     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- )O
-- GROUP BY O.CAR_ID
-- HAVING ROUND(AVG(DURATION), 1) >= 7
-- ORDER BY AVERAGE_DURATION DESC, O.CAR_ID DESC

-- 10/30
SELECT
    CAR_ID,
    TO_CHAR(ROUND(AVG(END_DATE - START_DATE + 1), 1), 'FM9990.0') AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(END_DATE - START_DATE + 1) >= 7
ORDER BY ROUND(AVG(END_DATE - START_DATE + 1), 1) DESC, CAR_ID DESC