-- 코드를 입력하세요
-- SELECT CONCAT(CONCAT(CONCAT(CONCAT(CONCAT('/home/grep/src/', B.BOARD_ID),'/'),file_id), FILE_NAME),file_ext)
-- FROM USED_GOODS_FILE F,
--     (SELECT *
--         FROM (SELECT BOARD_ID, VIEWS
--             FROM USED_GOODS_BOARD
--             ORDER BY VIEWS DESC
--           )
--         WHERE ROWNUM = 1
--      ) B
-- WHERE F.BOARD_ID = B.BOARD_ID
-- ORDER BY FILE_ID DESC

-- SELECT
-- '/home/grep/src/' || F.BOARD_ID || '/' || FILE_ID || FILE_NAME || FILE_EXT AS FILE_PATH
-- FROM USED_GOODS_BOARD B
-- JOIN USED_GOODS_FILE F
-- ON B.BOARD_ID = F.BOARD_ID
-- WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD )
-- ORDER BY FILE_ID DESC;

-- SELECT
--  *
-- FROM USED_GOODS_BOARD B
-- JOIN USED_GOODS_FILE F
-- ON B.BOARD_ID = F.BOARD_ID

-- 10/30
SELECT
    CONCAT(CONCAT(CONCAT(CONCAT(CONCAT('/home/grep/src/', B.BOARD_ID),'/'),file_id), FILE_NAME),file_ext) AS FILE_PATH
FROM (
         SELECT
             BOARD_ID
         FROM USED_GOODS_BOARD
         ORDER BY VIEWS DESC
             FETCH NEXT 1 ROWS ONLY
     ) B JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
ORDER BY F.FILE_ID DESC