-- 코드를 입력하세요
-- SELECT
--     ANIMAL_ID, NAME,
--     TO_CHAR(DATETIME, 'YYYY-MM-DD') AS 날짜
-- FROM ANIMAL_INS
-- ORDER BY ANIMAL_ID


-- SELECT ANIMAL_ID, NAME, TO_CHAR(DATETIME, 'YYYY-MM-DD') AS 날짜
-- FROM ANIMAL_INS
-- ORDER BY ANIMAL_ID

-- 11/01
SELECT
    ANIMAL_ID,
    NAME,
    TO_CHAR(DATETIME, 'YYYY-MM-DD') AS "날짜"
FROM ANIMAL_INS
ORDER BY ANIMAL_ID