-- 코드를 작성해주세요
-- 10/15
# SELECT
      #     A.ID,
          #     C.FISH_NAME,
          #     B.LENGTH
# FROM FISH_INFO A, (
    #     SELECT
#         FISH_TYPE,
#         MAX(LENGTH) AS LENGTH
#     FROM FISH_INFO
#     GROUP BY FISH_TYPE
# ) B, FISH_NAME_INFO C
      # WHERE A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.LENGTH AND C.FISH_TYPE = A.FISH_TYPE
      # ORDER BY A.ID

SELECT
    F1.ID,
    FNI.FISH_NAME,
    F1.LENGTH
FROM
    FISH_INFO F1
        JOIN
    FISH_NAME_INFO FNI ON F1.FISH_TYPE = FNI.FISH_TYPE
        JOIN
    (SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
     FROM FISH_INFO
     WHERE LENGTH IS NOT NULL
     GROUP BY FISH_TYPE) AS F2
    ON F1.FISH_TYPE = F2.FISH_TYPE AND F1.LENGTH = F2.MAX_LENGTH
ORDER BY
    F1.ID ASC;