-- -- 코드를 입력하세요
-- -- SELECT
-- --     -- COUNT(ANIMAL_TYPE) AS COUNT
-- --     COUNT(*) AS COUNT
-- -- FROM ANIMAL_INS
-- -- SELECT
-- --     ANIMAL_TYPE
-- -- FROM ANIMAL_INS


-- SELECT COUNT(*) AS COUNT
-- FROM ANIMAL_INS

-- 10/15
SELECT
    COUNT(*)
FROM ANIMAL_INS