-- 코드를 입력하세요
-- SELECT
--     COUNT(DISTINCT NAME) AS COUNT
-- FROM ANIMAL_INS
-- WHERE NAME IS NOT NULL

-- SELECT COUNT(DISTINCT NAME)
-- FROM ANIMAL_INS
-- WHERE NAME IS NOT NULL


-- 10/15
SELECT
    COUNT(DISTINCT NAME)
FROM ANIMAL_INS -- Null은 집계안함