-- 코드를 작성해주세요
-- 10/15
SELECT
    Year(E.DIFFERENTIATION_DATE) AS YEAR,
    ABS(E.SIZE_OF_COLONY - R.MAX_SIZE) AS YEAR_DEV,
    E.ID
FROM
    ECOLI_DATA E
    JOIN (
    SELECT
    Year(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
    ) R ON R.YEAR = Year(E.DIFFERENTIATION_DATE)
ORDER BY
    R.YEAR ASC,
    ABS(E.SIZE_OF_COLONY - R.MAX_SIZE) ASC;

# SELECT
      #     YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
#     (R.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV,
#     E.ID
# FROM
      #     ECOLI_DATA E
      # JOIN (
      #     SELECT
      #         YEAR(DIFFERENTIATION_DATE) AS YEAR,
      #         MAX(SIZE_OF_COLONY) AS MAX_SIZE
      #     FROM ECOLI_DATA
      #     GROUP BY YEAR(DIFFERENTIATION_DATE)
      # ) R ON R.YEAR = YEAR(E.DIFFERENTIATION_DATE)
      # ORDER BY
      #     YEAR ASC,
      #     YEAR_DEV ASC;
